export const GET_TOKEN = "GET_TOKEN";
export const SAVE_TOKEN = "SAVE_TOKEN";
export const REMOVE_TOKEN = "REMOVE_TOKEN";
export const LOADING = "LOADING";
export const ERROR = "ERROR";

export const FETCHING_DATA = "FETCHING_DATA"
export const ERROR_FETCHING_DATA = "ERROR_FETCHING_DATA"
export const DATA_FETCHED = "DATA_FETCHED";

export const VALID_USER = "VALID_USER";
export const INVALID_USER = "INVALID_USER";
export const LOGED_OUT = "LOGED_OUT";
export const USER_CREATED = "USER_CREATED";

export const FETCH_USER_DATA_SUCCESS = "FETCH_USER_DATA_SUCCESS";
export const FETCH_SPECIALITIES_SUCCESS = "FETCH_SPECIALITIES_SUCCESS";
export const FETCH_HEALTH_INSURANCES_SUCCESS = "FETCH_HEALTH_INSURANCES_SUCCESS";
export const FETCH_CLINICS_FOR_SPECIALITY_SUCCESS = "FETCH_CLINICS_FOR_SPECIALITY_SUCCESS";
export const BOOKING_SUCCESS = "BOOKING_SUCCESS";
export const FETCH_BOOKING_SUCCESS = "FETCH_BOOKING_SUCCESS";

export const REFRESHING = "REFRESHING";
export const FINISH_REFRESHING = "FINISH_REFRESHING";

export const COORDINATES_REFRESH = "COORDINATES_REFRESH";