export const GET_TOKEN = "GET_TOKEN";
export const SAVE_TOKEN = "SAVE_TOKEN";
export const REMOVE_TOKEN = "REMOVE_TOKEN";
export const LOADING = "LOADING";
export const ERROR = "ERROR";

export const VALID_USER = "VALID_USER";
export const INVALID_USER = "INVALID_USER";
export const VALIDATE_USER_BEGIN = "VALIDATE_USER_BEGIN";
export const LOGED_OUT = "LOGED_OUT";
export const USER_CREATED = "USER_CREATED";
export const ERROR_CREATING_USER = "ERROR_CREATING_USER";

export const FETCH_SPECIALITIES_PENDING = "FETCH_SPECIALITIES_PENDING";
export const FETCH_SPECIALITIES_SUCCESS = "FETCH_SPECIALITIES_SUCCESS";
export const FETCH_SPECIALITIES_ERROR = "FETCH_SPECIALITIES_ERROR";

export const FETCH_CLINICS_PENDING = "FETCH_CLINICS_PENDING";
export const FETCH_CLINICS_SUCCESS = "FETCH_CLINICS_SUCCESS";
export const FETCH_CLINICS_ERROR = "FETCH_CLINICS_ERROR";

export const FETCH_CLINICS_FOR_SPECIALITY_PENDING = "FETCH_CLINICS_FOR_SPECIALITY_PENDING";
export const FETCH_CLINICS_FOR_SPECIALITY_SUCCESS = "FETCH_CLINICS_FOR_SPECIALITY_SUCCESS";
export const FETCH_CLINICS_FOR_SPECIALITY_ERROR = "FETCH_CLINICS_FOR_SPECIALITY_ERROR";